    local function format_name(name)
        local formatted = name:gsub("%-", " ")
        return (formatted:gsub("^%l", string.upper))
    end

data:extend({
    {
    type = "fluid",
    name = "carbon-dioxide",
    default_temperature = 15,
    max_temperature = 31,
    heat_capacity = "0.8kJ",
    base_color = { r = 0.6, g = 0.0, b = 0.0 },
    flow_color = { r = 0.6, g = 0.0, b = 0.0 },
    icon = "__delirium__/graphics/icons/fluids/carbon-dioxide.png",
    icon_size = 1024,
    localised_name = {"", format_name("carbon-dioxide")},
    },
    {
    type = "fluid",
    name = "chlorine",
    default_temperature = 25,
    max_temperature = 143,
    heat_capacity = "0.5kJ",
    base_color = { r = 0.0, g = 1.0, b = 0.0 },
    flow_color = { r = 0.0, g = 0.7, b = 0.0 },
    icon = "__delirium__/graphics/icons/fluids/chlorine.png",
    icon_size = 1024,
    localised_name = {"", format_name("chlorine")},
    },
    {
    type = "fluid",
    name = "dirty-water",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    base_color = { r = 0.33, g = 0.24, b = 0.0 },
    flow_color = { r = 0.33, g = 0.24, b = 0.0 },
    icon = "__delirium__/graphics/icons/fluids/dirty-water.png",
    icon_size = 1024,
    localised_name = {"", format_name("dirty-water")},
    },
    {
    type = "fluid",
    name = "hydrogen",
    default_temperature = -200,
    max_temperature = 6000,
    heat_capacity = "0.1kJ",
    base_color = { r = 0.8, g = 0.8, b = 0.8 },
    flow_color = { r = 0.8, g = 0.8, b = 0.8 },
    icon = "__delirium__/graphics/icons/fluids/hydrogen.png",
    icon_size = 1024,
    localised_name = {"", format_name("hydrogen")},
    },
    {
    type = "fluid",
    name = "molten-iron",
    default_temperature = 1500,
    max_temperature = 5000,
    heat_capacity = "0.1kJ",
    base_color = { r = 0.7, g = 0.5, b = 0.2 },
    flow_color = { r = 0.7, g = 0.5, b = 0.2 },
    icon = "__delirium__/graphics/icons/fluids/molten-iron.png",
    icon_size = 1024,
    localised_name = {"", format_name("molten-iron")},
    },
    {
    type = "fluid",
    name = "nitrogen",
    default_temperature = -175,
    max_temperature = 1325,
    heat_capacity = "0.1kJ",
    base_color = { r = 0, g = 0.0, b = 1.0 },
    flow_color = { r = 0.0, g = 0.0, b = 1.0 },
    icon = "__delirium__/graphics/icons/fluids/nitrogen.png",
    icon_size = 1024,
    localised_name = {"", format_name("nitrogen")},
    },
    {
    type = "fluid",
    name = "oxygen",
    default_temperature = 15,
    max_temperature = 6000,
    heat_capacity = "0.1kJ",
    base_color = { r = 1.0, g = 0.0, b = 0.0 },
    flow_color = { r = 1.0, g = 0.0, b = 0.0 },
    icon = "__delirium__/graphics/icons/fluids/oxygen.png",
    icon_size = 1024,
    localised_name = {"", format_name("oxygen")},
    },
    {
    type = "fluid",
    name = "sulfur-dioxide",
    default_temperature = 15,
    max_temperature = 157,
    heat_capacity = "0.1kJ",
    base_color = { r = 0.5, g = 0.2, b = 0.0 },
    flow_color = { r = 0.5, g = 0.2, b = 0.0 },
    icon = "__delirium__/graphics/icons/fluids/sulfur-dioxide.png",
    icon_size = 72,
    localised_name = {"", format_name("sulfur-dioxide")},
    },
    {
    type = "fluid",
    name = "sulfur-trioxide",
    default_temperature = 35,
    max_temperature = 157,
    heat_capacity = "0.1kJ",
    base_color = { r = 0.7, g = 0.3, b = 0.0 },
    flow_color = { r = 0.7, g = 0.3, b = 0.0 },
    icon = "__delirium__/graphics/icons/fluids/sulfur-trioxide.png",
    icon_size = 64,
    localised_name = {"", format_name("sulfur-trioxide")},
    },
    {
    type = "fluid",
    name = "molten-glass",
    default_temperature = 1450,
    max_temperature = 5000,
    heat_capacity = "0.1kJ",
    base_color = { r = 0.7, g = 0.5, b = 0.2 },
    flow_color = { r = 0.7, g = 0.5, b = 0.2 },
    icon = "__delirium__/graphics/icons/fluids/molten-glass.png",
    icon_size = 1024,
    localised_name = {"", format_name("molten-glass")},
    },
    {
    type = "fluid",
    name = "dirty-water",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    base_color = { r = 0.33, g = 0.24, b = 0.0 },
    flow_color = { r = 0.33, g = 0.24, b = 0.0 },
    icon = "__delirium__/graphics/icons/fluids/dirty-water.png",
    icon_size = 1024,
    localised_name = {"", format_name("dirty-water")},
    },
    {
    type = "fluid",
    name = "sodium-aluminate",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    base_color = { r = 0.0, g = 0.44, b = 0.7 },
    flow_color = { r = 0.0, g = 0.44, b = 0.7 },
    icon = "__delirium__/graphics/icons/fluids/sodium-aluminate.png",
    icon_size = 1024,
    localised_name = {"", format_name("sodium-aluminate")},
    },
    {
    type = "fluid",
    name = "sodium-hydroxide-solution",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    base_color = { r = 0.0, g = 0.54, b = 0.7 },
    flow_color = { r = 0.0, g = 0.54, b = 0.7 },
    icon = "__delirium__/graphics/icons/fluids/sodium-hydroxide-solution.png",
    icon_size = 1024,
    localised_name = {"", format_name("sodium-hydroxide-solution")},
    },
    {
    type = "fluid",
    name = "salt-water",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    base_color = { r = 0.0, g = 0.24, b = 0.7 },
    flow_color = { r = 0.0, g = 0.24, b = 0.7 },
    icon = "__delirium__/graphics/icons/fluids/salt-water.png",
    icon_size = 1024,
    localised_name = {"", format_name("salt-water")},
    },
    {
    type = "fluid",
    name = "red-mud",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    base_color = { r = 0.7, g = 0.4, b = 0.0 },
    flow_color = { r = 0.7, g = 0.4, b = 0.0 },
    icon = "__delirium__/graphics/icons/fluids/red-mud.png",
    icon_size = 1024,
    localised_name = {"", format_name("red-mud")},
    },
})